name: Distribution tests 4

on:
  # Allow manual triggers for testing the action.
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'

  push:
    branches:
      - 'main'

jobs:
  test:
    name: Run distribution tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # we want to run the distribution tests on all major OSs, but it's occasionally too slow (or hangs or the forked process is not started at all..., not sure the cause) on windows.
        #os: [ubuntu-latest, macos-latest, windows-latest]
        #os: [ubuntu-latest, macos-latest]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
        java-package: jdk
    - name: Prepare caches
      uses: ./.github/actions/gradle-caches

    - name: Initialize gradle settings (${{ matrix.os }})
      run: ./gradlew localSettings

    - name: Run all distribution tests including GUI tests 1 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test

    - name: Run all distribution tests including GUI tests 2 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test

    - name: Run all distribution tests including GUI tests 3 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test

    - name: Run all distribution tests including GUI tests 4 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test

    - name: Run all distribution tests including GUI tests 5 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test

    - name: Run all distribution tests including GUI tests 6 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test

    - name: Run all distribution tests including GUI tests 7 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test

    - name: Run all distribution tests including GUI tests 8 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test

    - name: Run all distribution tests including GUI tests 9 (${{ matrix.os }})
      run: ./gradlew -p lucene/distribution.tests test
